from docx import Document
from docx.shared import Inches, Pt, RGBColor
from pathlib import Path
import re

root=Path(r'C:/Users/elian/Mismo')
src=Document(r'C:/Users/elian/OneDrive/Documentos/Nuevo Juego/GDD_v0.2.docx')
d=Document()
sec=d.sections[0]
sec.top_margin=sec.bottom_margin=Inches(.7)
sec.left_margin=sec.right_margin=Inches(.8)
for name in ['Normal','Title','Subtitle','Heading 1','Heading 2']:
 s=d.styles[name]; s.font.name='Calibri'; s.font.color.rgb=RGBColor(0,0,0)
d.styles['Normal'].font.size=Pt(11)
d.styles['Normal'].paragraph_format.space_after=Pt(6)
d.styles['Normal'].paragraph_format.line_spacing=1.05
d.styles['Title'].font.size=Pt(26)
d.styles['Heading 1'].font.size=Pt(17)
d.styles['Heading 2'].font.size=Pt(12)
def p(t): d.add_paragraph(t)
def h(t): d.add_heading(t,1)
def sub(t): d.add_heading(t,2)
d.add_heading('Mismo Game Design Document',0)
p('Versión 0.3 • Diseño consolidado • 7 de septiembre de 2026')
p('Mismo es un juego de fantasía en tercera persona donde explorar, dominar el movimiento y cambiar de equipamiento definen la experiencia. Este documento reúne la visión de largo plazo, el alcance del prototipo y el diseño acordado de dos armas con una sola activa.')
p('El prototipo conserva una región, una espada y un cinturón. El sistema de dos armas es una decisión de diseño para su evolución; su incorporación al prototipo y la segunda arma concreta quedan por planificar. La progresión detallada se presenta como propuesta pendiente de aprobación.')
sub('Lectura y estado de las decisiones')
p('Las secciones 1 a 6 conservan el alcance de paisaje y combate de la versión 0.2. Las secciones 7 a 10 integran la visión original y las decisiones de equipamiento posteriores. La sección 11 propone progresión y la sección 12 reúne decisiones pendientes. Ninguna descripción de arquitectura nueva implica que ya esté implementada.')
for para in src.paragraphs:
 t=para.text.strip()
 if t.startswith('1 Visión'): copying=True
 elif t.startswith('7 Visión'): break
 elif 'copying' not in locals(): continue
 if not t: continue
 if re.match(r'^[1-6] ',t): h(t)
 elif para.style.name.startswith('Heading'): sub(t)
 else: p(t)
h('7 Visión de largo plazo')
sub('Identidad y referencias')
p('El personaje no tiene clase fija. Espada, arco, bastón, martillo y otras armas representan estilos diferentes. Cambiar de arma debe transformar ritmo, alcance y decisiones sin exigir crear otro personaje. Cube World clásico orienta exploración, cámara y volúmenes; Dark Souls, Battlerite, World of Warcraft, Pokémon y Alundra son referencias conceptuales, sin reproducir íntegramente sus sistemas.')
sub('Progreso y exploración')
p('La visión incluye nivel global del personaje, progreso de armas, materiales, loot raro, builds, enemigos relevantes, elites, dungeons y secretos. La exploración debe provocar curiosidad y recompensar desvíos. No depende de un sistema tradicional de quests; futuros encargos serían excepcionales y ligados a descubrimientos.')
p('Pueblos futuros pueden ofrecer comercio, herrería, almacenamiento y preparación. Regiones y biomas pueden tener niveles mínimos y escalado parcial; fórmulas y valores no están definidos. Criaturas y monturas adaptadas a entornos terrestres, acuáticos o aéreos son posibilidades futuras.')
sub('Equipamiento y expansión')
p('Arma y cinturón son los slots centrales. Accesorios podrán aportar personalización si cambian decisiones de juego. No se prevén slots tradicionales de armadura que solo añadan números, ni atributos complejos sin una necesidad concreta.')
p('Se desea single-player completo antes de cooperativo con anfitrión y posibles modalidades de PvP. Networking, autoridad y sincronización no se implementan en Scope 0. Mundo infinito, cuevas volumétricas, nuevos biomas y carga dinámica se evaluarán después de validar paisaje y combate.')
h('8 Dos armas y alternancia')
sub('Reglas acordadas')
p('El jugador prepara dos armas y utiliza una por vez. La activa determina ataque básico y habilidades Q, E y R. El cinturón conserva el dash en C independientemente del arma activa. No existen clases ni uso simultáneo de ambos kits.')
p('Se puede alternar entre las dos armas durante el combate siempre que no se esté atacando. El ataque incluye su recuperación: cambiar no permite recortar esa fase. Reemplazar cuáles son las dos armas equipadas se realiza fuera de combate, sin exigir estar en un pueblo.')
p('Al alternar se conservan los cooldowns de cada arma. Los efectos ya creados, como áreas y proyectiles, mantienen su autor y sus reglas de duración. El cambio no reinicia habilidades ni modifica retroactivamente efectos existentes.')
p('Cada arma conserva su progreso al quedar inactiva. Equipar un arma nueva permite probar otro estilo, pero no concede automáticamente su nivel máximo ni sus mejoras.')
sub('Representación visual')
p('El arma activa se muestra en la mano y la secundaria en la espalda. Al alternar, ambas intercambian sus puntos de sujeción y el kit activo cambia en el mismo momento. La solución inicial es instantánea, sin animación de desenfundado.')
p('Cada arma define ajustes de posición y rotación para mano y espalda. El modelo guardado en la espalda es visual y no mantiene hitboxes ofensivas activas. Los ajustes para arcos y armas grandes deben revisarse sobre el personaje.')
sub('Repertorio de habilidades')
p('Se mantiene ataque básico y tres habilidades activas por arma. Un repertorio mayor del cual seleccionar esas tres fuera de combate queda como propuesta de expansión. Los kits definitivos, sus desbloqueos y las combinaciones válidas todavía no están diseñados.')
h('9 Arquitectura propuesta de armas y habilidades')
p('La dirección propuesta utiliza composición: cada arma referencia habilidades, y cada habilidad combina comportamientos reutilizables. Debe adaptarse a los sistemas existentes de daño, salud, hitboxes, stagger, parry y movimiento; no crear una segunda arquitectura paralela. Las clases siguientes expresan responsabilidades propuestas, no una auditoría del código actual.')
sub('Definiciones y estado')
p('WeaponDefinition guarda presentación, ataque básico y referencias a habilidades. AbilityDefinition guarda parámetros, fases, costos, cooldown y reglas de cancelación. Ambas pueden ser ScriptableObjects compartidos. El estado mutable no se guarda en esas definiciones.')
p('EquipmentController conserva las dos armas y cuál está activa. AbilityRunner valida el uso y ejecuta preparación, actividad y recuperación. AbilityExecution guarda tiempos, blancos ya golpeados y recursos temporales de una ejecución. El estado de cooldown debe sobrevivir al cambio de arma y al final de esa ejecución.')
p('El progreso del jugador con un tipo de arma y las mejoras de un ejemplar deben poder representarse por separado. La elección de progresión por familia o por objeto sigue pendiente; no se anticipa todavía un inventario complejo.')
sub('Comportamientos reutilizables')
p('MoveCaster solicita desplazamiento al controlador. MeleeHit detecta blancos y emite impactos. OpenParryWindow registra una defensa temporal. SpawnArea y SpawnProjectile crean entidades con vida propia. Daño, empuje, stagger y estados se resuelven a través de sistemas comunes.')
p('Un impacto pasa por la defensa antes de aplicar consecuencias. La ventana de parry puede configurar duración, ángulo, ataques aceptados y respuesta al éxito. Una cancelación cierra hitboxes, ventanas defensivas y solicitudes de movimiento que pertenecen a la ejecución.')
p('Desplazamiento voluntario y empuje recibido comparten el acceso al controlador de movimiento, pero mantienen reglas distintas de resistencia e interrupción. Ninguna habilidad debe mover al personaje ignorando colisiones o competir sin resolución con otro movimiento.')
sub('Aplicación gradual')
p('Primero extraer las piezas que exige la espada existente. Después validar reutilización mediante una segunda arma pequeña en una prueba separada, si se aprueba esa entrega. No construir todavía un editor universal de nodos. Una habilidad excepcional puede agregar comportamiento específico sin modificar el controlador del jugador.')
h('10 Áreas y efectos en el mundo')
p('Separar autor, ubicación, selección de objetivos y efectos. Una habilidad puede originarse en el personaje, fijarse en un punto del suelo o viajar. Una zona fija no sigue al personaje ni depende de que continúe su animación.')
p('AreaInstance conserva autor, posición, orientación, forma, tamaño, duración, frecuencia de aplicación y filtros de objetivos. La misma detección circular puede aplicar daño, curación, ralentización o empuje. ProjectileInstance conserva trayectoria e información de sus impactos.')
p('La selección de suelo debe validar alcance y superficie. En relieve escalonado, limitar altura y comprobar obstáculos cuando corresponda para evitar afectar blancos en otra planta o detrás de una pared. El indicador visual debe coincidir razonablemente con el volumen efectivo.')
p('Los efectos creados conservan los parámetros necesarios al lanzarse: alternar de arma no los convierte en efectos del arma nueva. Debe definirse por habilidad si un área persiste al morir su autor y cómo evita impactos repetidos no deseados.')
h('11 Progresión de armas propuesta pendiente')
p('Esta sección es una propuesta para discutir. Todavía no fija niveles máximos, porcentajes, costos, fórmulas de experiencia ni un calendario definitivo de desbloqueos. No forma parte de la implementación de Scope 0.')
sub('Dos formas de mejorar')
p('Dominio del tipo de arma: experiencia obtenida al usar de forma efectiva espada, arco o martillo. Permanece al cambiar de equipamiento. Propuesta: compartir este dominio entre ejemplares del mismo tipo para que encontrar otra espada no obligue a reaprender su estilo.')
p('Mejora del ejemplar: inversión de materiales para aumentar el rendimiento del objeto concreto. Permite que adquirir un arma nueva conserve el aprendizaje, pero requiera mejorar ese objeto. Los materiales, rarezas y límites se diseñarán más adelante.')
sub('Progresión con identidad temprana')
p('Propuesta: entregar temprano un kit representativo con ataque básico y habilidades que permitan evaluar el estilo. Los primeros niveles no deberían ocultar durante horas la mecánica central del arma. Los niveles posteriores pueden ofrecer variantes o especializaciones que se eligen fuera de combate.')
p('Como esquema inicial de discusión, los niveles intermedios podrían otorgar mejoras pequeñas y acotadas, y ciertos hitos una elección de variante. No es necesario crear una habilidad nueva en cada nivel. La curva exacta se decidirá después de probar el combate.')
p('Ejemplos de variantes para estudiar: una estocada que prioriza alcance o stagger; un área que prioriza radio o duración; un parry cuya respuesta otorga ventaja ofensiva o defensiva. Cada variante debería tener un costo o contrapartida comprensible, evitando acumular todas las ventajas.')
sub('Experiencia y balance')
p('Propuesta: asignar progreso según contribución efectiva, incluyendo daño y acciones defensivas útiles, sin exigir el último golpe. Con dos armas, la atribución debe reconocer cuál realizó la acción y evitar premiar simplemente llevar un arma en la espalda. Las reglas para objetivos débiles, apoyos y efectos persistentes quedan por definir.')
p('Separar potencia y variedad permite probar una nueva arma sin que ya esté maximizada. El nivel global no debería borrar toda dificultad de progresar un arma nueva ni volverla tan débil que resulte imposible evaluarla. Ambos extremos requieren pruebas antes de fijar números.')
h('12 Decisiones pendientes y validación futura')
p('Definir segunda arma, kits iniciales, tecla para alternar, criterio de entrada y salida de combate y comportamiento del cambio durante parry, dash, stagger, canalización o apuntado. La regla confirmada prohíbe alternar durante ataque y recuperación; no resuelve por sí sola todos esos estados.')
p('Decidir si alternar tiene un tiempo propio o cooldown, si se permiten dos ejemplares del mismo tipo y cómo comparten cooldowns. Estas reglas deben evitar reinicios o duplicaciones de habilidades y conservar la claridad de los controles.')
p('Aprobar o revisar dominio por familia, mejoras por ejemplar, experiencia, niveles, hitos, variantes y selección de tres habilidades. Determinar cuándo incorporar dos armas al plan de entregas sin presentar la ampliación como trabajo ya realizado.')
p('Al implementar alternancia, verificar: bloqueo durante ataque y recuperación; actualización simultánea de modelos y habilidades; cooldown conservado al volver; parry y hitboxes correctamente cerrados; área persistente independiente del arma activa; progreso atribuible al arma que actuó.')
h('13 Historial y procedencia')
p('Versión 0.1: visión inicial, equipamiento sin clases, progresión de armas y prototipo vertical. Versión 0.2: región generada en el editor, estética voxel y alcance técnico acotado. Versión 0.3: consolida esa visión y alcance, incorpora dos armas alternables, su representación visual y una arquitectura propuesta; separa la progresión pendiente de las decisiones confirmadas.')
p('Fuentes de diseño: GDD v0.1, GDD v0.2 y decisiones del autor del 7 de septiembre de 2026. En conflictos sobre el paisaje y Scope 0 prevalece la versión 0.2. Las decisiones posteriores de equipamiento definen el diseño futuro sin declarar su implementación.')
p('Referencias conservadas de la versión 0.2: Cube World en Steam; documentación oficial de Unity sobre Mesh y Mathf.PerlinNoise. Orientan estética y herramientas, sin afirmar conocer el algoritmo interno de Cube World.')
p('https://store.steampowered.com/app/1128000/Cube_World/')
p('https://docs.unity3d.com/6000.0/Documentation/ScriptReference/Mesh.html')
p('https://docs.unity3d.com/6000.0/Documentation/ScriptReference/Mathf.PerlinNoise.html')
out=root/'GDD_v0.3_consolidado.docx'
d.save(out)
print(out)
