from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from pathlib import Path
D=Document(); s=D.sections[0]; s.page_width=Inches(8.27); s.page_height=Inches(11.69); s.top_margin=s.bottom_margin=Inches(.7); s.left_margin=s.right_margin=Inches(.8)
for n in ['Normal','Title','Subtitle','Heading 1','Heading 2']:
 st=D.styles[n]; st.font.name='Calibri'; st.font.color.rgb=RGBColor(0,0,0)
D.styles['Normal'].font.size=Pt(11); D.styles['Normal'].paragraph_format.space_after=Pt(7); D.styles['Normal'].paragraph_format.line_spacing=1.06
D.styles['Title'].font.size=Pt(28); D.styles['Heading 1'].font.size=Pt(19); D.styles['Heading 2'].font.size=Pt(13)
def p(t): D.add_paragraph(t)
def h(t): D.add_heading(t,2)
def page(t): D.add_page_break(); D.add_heading(t,1)
def table(headers,rows,widths):
 t=D.add_table(rows=1, cols=len(headers)); t.autofit=False
 for c,w in zip(t.columns,widths): c.width=Inches(w)
 for i,row in enumerate([headers]+rows):
  cells=t.rows[0].cells if i==0 else t.add_row().cells
  for j,(c,txt) in enumerate(zip(cells,row)):
   c.width=Inches(widths[j]); c.text=txt; c.vertical_alignment=1
   pr=c._tc.get_or_add_tcPr(); sh=OxmlElement('w:shd'); sh.set(qn('w:fill'),'DFE8ED' if i==0 else ('F5F7F8' if i%2==0 else 'FFFFFF')); pr.append(sh)
   mar=OxmlElement('w:tcMar')
   for side in ['top','left','bottom','right']:
    e=OxmlElement('w:'+side); e.set(qn('w:w'),'90'); e.set(qn('w:type'),'dxa'); mar.append(e)
   pr.append(mar)
   for para in c.paragraphs:
    para.paragraph_format.space_after=Pt(3); para.paragraph_format.space_before=Pt(3)
    for r in para.runs: r.font.size=Pt(10); r.bold=i==0
  rp=t.rows[i]._tr.get_or_add_trPr(); ns=OxmlElement('w:cantSplit'); rp.append(ns)
  if i==0: rp.append(OxmlElement('w:tblHeader'))
 borders=OxmlElement('w:tblBorders')
 for side in ['top','left','bottom','right','insideH','insideV']:
  e=OxmlElement('w:'+side); e.set(qn('w:val'),'single'); e.set(qn('w:sz'),'4'); e.set(qn('w:color'),'D9D9D9'); borders.append(e)
 t._tbl.tblPr.append(borders)
 D.add_paragraph().paragraph_format.space_after=Pt(0)
D.add_heading('Mismo Game Design Document',0)
p('Versión 0.4 consolidada · 8 de septiembre de 2026')
p('Documento de referencia del diseño y del prototipo actual. Reúne la visión original, la región voxel, las decisiones de equipamiento, el addendum de combate y los cambios implementados hasta esta fecha. Reemplaza las descripciones anteriores que entren en conflicto con esta versión.')
p('Mismo es un juego de fantasía en tercera persona donde el jugador explora con un mismo personaje y construye su estilo mediante sus armas. La base actual permite probar espada y arco, crear oportunidades mediante defensas y posicionamiento, y recorrer una región completa de prueba.')
p('Esta es la versión final de esta consolidación. El balance, la progresión y el contenido futuro siguen abiertos. Tener un sistema implementado no significa que su dificultad o su sensación de juego estén aprobadas.')
h('Estado general')
table(['Área','Estado al cierre'],[
['Movimiento y cámara','Implementados con sprint, doble salto, dash y apuntado libre.'],['Equipamiento y combate','Dos armas, habilidades reutilizables, Focus, Posture y defensas perfectas implementados.'],['Mundo','Región voxel guardada, goblins, Elite, secreto, boss y reinicio del intento.'],['Presentación y acceso','Menú, opciones de audio, minimapa oblicuo, números de daño y muerte en cubitos.'],['Progresión y guardado','Pendientes. No hay niveles funcionales de armas, mejoras ni persistencia de partida.'],['Distribución','Existe un ZIP anterior; hay que generar otro para incluir los últimos cambios de combate.']],[1.8,4.85])
h('Cómo utilizar este documento')
p('Las secciones de funcionamiento describen el prototipo existente. Las reglas acordadas aún sin interfaz y las propuestas se identifican expresamente. Los valores numéricos son ajustes de prueba, no compromisos de balance definitivo. El último apartado ordena los siguientes pasos y sus criterios de cierre.')
page('1 Visión y alcance')
h('Fantasía y pilares')
p('Explorar un mundo fantástico, descubrir enemigos y secretos, dominar las armas preferidas y enfrentar desafíos progresivamente más difíciles. Cambiar de arma debe cambiar ritmo, alcance y decisiones sin exigir crear otro personaje. No existen clases tradicionales.')
p('Moverse debe resultar satisfactorio incluso sin combate. Los encuentros priorizan uno a cinco enemigos relevantes, con ataques reconocibles y oportunidades para responder. La dificultad procede de lectura, timing, posición y compromiso; aumentar vida o daño no reemplaza esos requisitos.')
p('La exploración debe despertar curiosidad por el paisaje y recompensar desvíos. No depende de una lista de quests. Cube World clásico orienta cámara, volúmenes y sensación de exploración; Dark Souls, Battlerite, World of Warcraft, Pokémon y Alundra son referencias conceptuales, sin adoptar sus sistemas completos.')
h('Loop de la región actual')
p('Comenzar en el menú → aparecer en el pueblo → explorar y combatir → descubrir el Elite o el secreto opcionales → enfrentar al boss → abrir el paso posterior → terminar el recorrido o iniciar otro intento.')
p('El secreto cura y ayuda a preparar el encuentro final. El boss no exige completar todos los encuentros, una quest o una llave. La victoria abre un paso conceptual, sin cargar otro bioma. Al morir se recarga la región y el jugador vuelve al pueblo; se reinician enemigos, boss y recompensa, sobre el mismo paisaje.')
h('Alcance actual y expansión autorizada')
p('El Scope 0 original creció de una espada y una región manual a dos armas y un paisaje generado en el editor. La entrega vigente conserva un personaje, un cinturón, un goblin base con variante Elite, un boss y una sola región. El objetivo continúa siendo validar movilidad, combate y exploración antes de multiplicar contenido.')
h('Visión futura conservada')
p('Progreso global del personaje y de sus armas; materiales, loot raro y builds; dungeons y secretos; nuevas regiones, biomas, criaturas y posibles monturas adaptadas a distintos entornos. Los pueblos podrán ofrecer comercio, herrería y almacenamiento. El nivel mínimo por región y un posible escalado parcial permanecen sin fórmulas.')
p('El juego debe funcionar completamente en single-player antes de cooperativo con anfitrión. PvP opcional, incluida una posible arena 3v3, queda fuera de esta etapa. También quedan fuera mundo infinito, terreno destructible, cuevas volumétricas, economía y crafting complejos, árboles de talentos y un catálogo amplio de armas. No se incorporan clases ni armaduras tradicionales que solo añadan estadísticas.')
page('2 Movimiento equipamiento y controles')
table(['Entrada','Acción'],[['WASD y mouse','Movimiento relativo a cámara y órbita libre.'],['Shift','Sprint con consumo de stamina.'],['Espacio','Salto y segundo salto en el aire; soltar reduce altura.'],['Click izquierdo','Básico del arma activa; mantener carga el arco.'],['Q E R','Tres habilidades del arma activa.'],['C','Dash del cinturón, independiente del arma y de la stamina.'],['Tab','Alternar entre las dos armas equipadas.'],['Escape','En gameplay libera el cursor; en opciones vuelve al menú.']],[1.7,4.95])
h('Movimiento y apuntado actuales')
p('La cámara es relativamente alejada, con rotación libre y sin dependencia de lock-on. La mira del arco se sitúa al 60 % de la altura de pantalla desde abajo, sobre el personaje. Cámara y lanzamiento comparten el objetivo; la flecha parte del arco. La mira puede ajustarse durante la preparación; una zona de suelo conserva el punto elegido.')
p('El modelo se inclina suavemente 6 grados al avanzar y 12 durante sprint, sin inclinar la colisión ni alterar la autoridad de giro del motor. El dash conserva dirección y respeta paredes. La ruta principal no debe requerir doble salto ni dash para llegar al boss.')
h('Dos armas y una sola activa')
p('El arma activa aporta básico y Q, E, R. La secundaria permanece en la espalda. Tab intercambia modelos y kit de inmediato, sin animación de desenfundado. Cada arma ajusta agarre, posición y rotación; el modelo guardado no aplica golpes.')
p('La implementación bloquea alternancia durante preparación, actividad, recuperación y dash. Cambiar no permite cortar un ataque. Los cooldowns continúan al alternar y al reequipar; definiciones idénticas comparten cooldown dentro del mismo jugador. Focus es común a ambas armas.')
p('Reemplazar cuáles son las dos armas se permite fuera de combate, sin exigir un pueblo. El sistema considera daño y persecución enemiga, con un período inicial configurable de seis segundos. Esta regla existe en código, pero todavía no hay inventario ni pantalla de selección para el jugador.')
h('Recursos')
p('Vida determina supervivencia. Stamina sostiene sprint y ciertas habilidades; no condiciona el dash básico. Focus recompensa buena ejecución y habilita ataques potentes. Los cooldowns empiezan al aceptar la habilidad y usan tiempo de juego. El progreso futuro del arma será independiente de estos recursos temporales.')
page('3 Combate y oportunidades')
h('Principio de combate')
p('Leer → responder → crear una apertura → preparar una acción comprometida → aprovecharla. Esperar cooldowns o mantener el básico no debería dominar todos los encuentros. La espada asume proximidad; el arco necesita tiempo y espacio para preparar sus disparos.')
h('Posture y ruptura')
p('Posture es una defensa enemiga separada de la vida. Goblins comienzan con 70 y el boss con 150. Regenera 9 por segundo después de tres segundos sin daño de Posture. Al llegar a cero provoca una vulnerabilidad de dos segundos; golpes adicionales no prolongan esa ruptura. Al terminar se restaura la barra.')
p('Este mecanismo sustituye el stagger automático por umbral de daño de vida. La recuperación de ataques enemigos y la ruptura son aperturas aprovechables; Opening expresa esa condición, no una tercera barra. Un parry sin ruptura interrumpe brevemente la ofensiva.')
table(['Acción precisa','Recompensa actual'],[['Perfect Parry','Primeros 0,09 s de defensa frontal válida: 35 de Posture al atacante y 20 Focus.'],['Parry normal','Resto de la ventana válida: 12 de Posture, sin Focus perfecto.'],['Perfect Dodge','Contacto real de un ataque en los primeros 0,085 s de esquiva: 20 Focus una vez por esquiva.'],['Golpe por espalda','8 Focus.'],['Golpe durante apertura','6 Focus; si también es espalda, se prioriza espalda y no se suman ambos premios.']],[1.6,5.05])
h('Confirmación de defensas')
p('Perfect Parry y Perfect Dodge activan una ralentización compartida de 0,12 segundos reales al 40 % de velocidad. Deben pasar al menos 1,5 segundos reales entre pulsos. Se restaura el tiempo al terminar. El parry normal muestra PARRY; el perfecto se distingue con PARRY PERFECTO y la recompensa correspondiente. La ralentización global solo corresponde al prototipo individual.')
p('Pulsar dash sin un ataque real no concede Focus. La invulnerabilidad posterior a recibir daño tampoco equivale a una esquiva perfecta. Focus tiene máximo 100, permanece al alternar armas y al curarse, y se reinicia al morir. La Q del arco consume 20 al iniciar.')
h('Daño direccional')
p('Frente enemigo: 85 % del daño; lateral: 100 %; espalda: 120 %. Espalda multiplica daño de Posture por 1,5 y una apertura por 1,4. La dirección se evalúa al impacto usando el ataque entrante. Las áreas verticales de lluvia no reciben ventajas de espalda ni distancia. Weakpoints anatómicos siguen pendientes.')
page('4 Kits actuales y balance de prueba')
h('Espada')
p('Click ejecuta un combo de tres golpes. Los primeros dos permiten ramificar hacia Q, E o C desde el 65 % de su etapa y durante la transición correspondiente. El buffer de intención es de 0,14 segundos. El golpe final conserva su recuperación; no habilita una cancelación libre de toda la cadena.')
table(['Entrada','Función'],[['Click','Combo corto que permite continuar o preparar una respuesta.'],['Q','Estocada con desplazamiento y golpe.'],['E','Ventana de parry de 0,16 s; los primeros 0,09 s pueden ser perfectos.'],['R','Giro de daño en área alrededor del personaje.']],[1.0,5.65])
h('Arco')
table(['Acción','Daño base','Preparación','Cooldown'],[['Click básico','8','0,40 a 1,20 s','0,85 s'],['Q potente','24','0,65 s','3 s'],['E retirada','6','0,45 s','4 s'],['R lluvia','5 por descarga','0,70 s y caída','7 s']],[1.75,1.35,2.0,1.55])
p('Daño antes de carga y modificadores. Un toque del básico completa la tensión mínima; mantener incrementa daño y Posture hasta liberar automáticamente a 1,20 s. Su recuperación es 0,35 s. Q tiene 45 de daño base a Posture y cuesta 12 stamina más 20 Focus. E cuesta 12 stamina y tiene 0,30 s de recuperación; tanto el disparo como la retirada esperan el final de su preparación. R cuesta 20 stamina.')
p('Todas las acciones ofensivas del arco tienen preparación. Durante ella, la movilidad solicitada baja al 40 % y recibir daño válido interrumpe antes de liberar. C puede cancelarla. Interrumpir o cancelar conserva los recursos gastados y el cooldown iniciado. No borra proyectiles ni áreas que ya salieron.')
h('Distancia y lluvia')
p('Hasta dos metros, los proyectiles sufren una penalización del 20 % que desaparece gradualmente a diez metros. Además reciben una bonificación suave de hasta 7,5 %, con tope a dieciocho metros. La distancia se mide entre origen e impacto; moverse después de disparar no la redefine. La mayor ventaja del rango debe seguir siendo el tiempo disponible para preparar.')
p('R fija una zona de radio 2,5 m con duración de tres segundos y descargas cada 0,6 s. Flechas visuales caen desde cinco metros; sus nueve flechas por descarga no multiplican el daño. El área aplica el pulso tras la caída y permanece independiente del personaje. Usa bow_B_withString y arrow_B como visuales del kit.')
page('5 Enemigos mundo y exploración')
h('Enemigos actuales')
p('El goblin detecta al jugador, navega, se posiciona, anuncia un golpe y una carga, recibe impactos y muere. El Elite reutiliza esa base con diferenciación visual. Ambos deben dejar espacio para reconocer preparación y recuperación. No se declara implementado un sistema universal de tiers y modificadores.')
p('La IA del goblin y su variante observa preparaciones ranged al decidir una acción: prioriza una carga disponible si está en rango y cierra más distancia antes de posicionarse. Conserva aviso y dirección fijada; no recibe daño o velocidad extra ocultos por enfrentar al arco. El boss conserva sus patrones y agresividad, con Posture y aperturas integrados.')
h('Región guardada desde el editor')
p('VoxelRegion_7319 es la escena jugable principal. El generador produce relieve y vegetación a partir de semilla y configuración; guarda mallas y escena. Durante Play no genera otro mundo. Pueblo, rutas, secreto y encuentros usan ubicaciones diseñadas, revisadas sobre el paisaje.')
p('El terreno usa mapa de alturas escalonado: celdas de un metro, escalones iniciales de 0,25 m y sectores de 32 m; tamaño configurable entre 256 y 384 m. Se agrupan caras expuestas en mallas con colisión. No se crea un objeto por cubito ni se ofrece edición de bloques. El fondo distante aporta horizonte sin colisión.')
p('Caminos y claros conectan pueblo, cuatro goblins base, un Elite, ruina lateral y boss. Los pequeños escalones deben poder caminarse. Las copas y plantas no deben ocultar telegraphs; la vegetación menor es decorativa y los troncos tienen colisión. Se conserva la escena manual InitialRegion como prueba anterior.')
h('Secreto muerte y victoria')
p('La ruina abierta recompensa el desvío con una restauración del 40 % de vida máxima, una vez por intento. No se consume con vida completa. El acceso es opcional y debe permitir volver sin quedar atrapado. No existe dungeon volumétrico bajo el terreno.')
p('La arena del boss mantiene entrada para retirada y salida posterior bloqueada hasta ganar. Morir recarga la escena tras dos segundos, devuelve al pueblo y reinicia el intento completo. No hay pérdida de experiencia, equipo ni recuperación de almas; tampoco guardado de avance. La desintegración visual no representa loot físico.')
h('Criterios de calidad del recorrido')
p('Horizonte abierto, sin una gran pared rectangular dominando la región; referencias para orientarse; grupos que no se unan accidentalmente; rutas sin saltos obligatorios constantes, grietas ni escapes. La duración deseada de 8 a 12 minutos sigue siendo orientativa, no un resultado medido. Rendimiento y ritmo deben verificarse en una build actual y hardware conocido.')
page('6 Presentación menú y sonido')
h('Presentación de combate y personaje')
p('El arco se sujeta al esqueleto visible con una pose de dos brazos; la mano de tensado acompaña la preparación. Es presentación procedural, sin un clip definitivo de tensado de cuerda. La corrección de rotación permite orientar al personaje manteniendo inclinación al correr.')
p('El HUD muestra vida, stamina, Focus, habilidades, cooldowns, arma activa y carga. Los enemigos muestran vida y Posture; la ruptura y las defensas tienen confirmación. Los números representan la vida realmente descontada, evitando exagerar el daño por encima de la vida restante.')
p('La muerte del jugador y enemigos oculta las mallas y emite partículas cúbicas que aproximan sus colores y silueta. El límite actual es 240 cubitos sin colliders individuales, con limpieza a los dos segundos; no es una conversión real de toda la malla a voxels. Revivir restaura la representación. Los números de daño duran un segundo, con máximo 64 simultáneos.')
p('El minimapa usa cámara ortográfica oblicua para mostrar relieve, mantiene norte arriba y una cobertura aproximada de 90 m. Las botas con animación independiente y el daño con aturdimiento por caída fuerte siguen pendientes; no forman parte de la entrega actual.')
h('Menú principal y opciones')
p('MainMenu es la primera escena: Comenzar carga VoxelRegion_7319, Opciones abre controles de sonido y Salir cierra la aplicación. El menú usa un Canvas editable y un paisaje voxel sencillo. Mismo continúa como título provisional. No hay todavía menú de pausa en gameplay.')
p('Opciones ofrece sliders independientes de Música, Efectos e Interfaz. Se guardan localmente y se aplican mediante el mixer. La curva se ajustó para que bajar a 70 % no silencie casi todo: 100 % equivale a 0 dB, 70 % aproximadamente a −1,55 dB y 0 % a silencio. La conversión actual es 10 log10 del valor normalizado, con cero tratado aparte.')
p('AudioManager, AudioEvents y MusicController se integraron desde el proyecto anterior. Los sonidos existentes se enrutan a efectos. Incorporar la estructura de audio no significa que ya exista una selección final de música o nuevos clips asignados.')
h('Estado de distribución')
p('Existe Mismo-Playtest-2026-09-07.zip para Windows, con menú y región. Ese paquete es anterior al nuevo combate y a los ajustes del 8 de septiembre. No debe usarse como evidencia de esta versión: el siguiente envío requiere compilar y comprobar una build actualizada.')
page('7 Arquitectura de referencia')
p('La base utiliza definiciones configurables, estado por ejecución y comportamientos reutilizables. Agregar armas debe reutilizar preparación, impactos, desplazamientos, defensas y áreas, sin convertir el controlador del jugador en una lista de excepciones por arma.')
table(['Responsabilidad','Pieza actual'],[['Datos compartidos','WeaponDefinition referencia básico y habilidades. AbilityDefinition configura fases, costos, curvas y acciones.'],['Equipamiento','EquipmentLoadout conserva dos armas y la activa; valida alternar y reemplazar.'],['Ejecución','AbilityRunner valida condiciones, tiempos, buffer, carga e interrupciones. AbilityExecution conserva estado de cada uso.'],['Acciones','AbilityAction permite componer golpe, desplazamiento, defensa, proyectil y área.'],['Impactos','DamageInfo transporta origen, autor, identidad, daño y propiedades. DamageReceiver.Resolve devuelve HitResult y emite Resolved.'],['Estado defensivo','DefenseWindow resuelve ventanas; CombatState conserva Focus, Posture y aperturas. Health conserva vida.'],['Movimiento','PlayerMotor mantiene autoridad sobre desplazamiento, colisiones y rotación.'],['Efectos persistentes','ProjectileInstance y AreaInstance conservan parámetros de lanzamiento y vida propia.']],[1.6,5.05])
h('Reglas de integración')
p('El estado mutable del combatiente no se almacena en los ScriptableObjects compartidos. La identidad del ataque evita resolver daño y recompensas otra vez por contactos repetidos. El contrato antiguo de daño y la espada básica conservan adaptadores para escenas y componentes anteriores.')
p('Cancelar limpia ventanas y desplazamientos de la ejecución. Los efectos liberados conservan su autor y no se transforman al alternar; pueden persistir aunque el autor muera. Una zona de suelo valida altura y obstáculos para no afectar sin criterio otra planta o el otro lado de una pared.')
p('La presentación escucha resultados del combate. CombatTimeFeedback centraliza ralentizaciones y restaura el tiempo; una futura versión multijugador tendrá que revisar este feedback global. El generador del mundo no define estadísticas ni reglas de combate. No se necesita ahora un editor universal de nodos.')
h('Dónde ajustar')
p('Assets/Data/Weapons contiene kits y habilidades; Assets/Resources/CombatRules.asset contiene reglas comunes de dirección, distancia y defensas; StartingWeapons define el equipamiento inicial. Docs/CombatV2.md, WeaponSystem.md, VoxelRegion.md y MainMenu.md amplían los detalles técnicos. Ante documentación histórica, esta consolidación incorpora las correcciones recientes.')
page('8 Progresión pendiente y siguientes pasos')
h('Progresión de armas propuesta para decidir')
p('Todavía no se implementan experiencia, niveles, materiales ni desbloqueos. La regla acordada es que cambiar de arma permita probar otro estilo sin recibir automáticamente su máximo nivel. Se propone separar dominio de la familia de arma de mejoras del ejemplar: aprender espada se conserva al encontrar otra espada, mientras cada objeto puede requerir inversión propia.')
p('Propuesta de bajo costo: ofrecer temprano el kit representativo; usar niveles intermedios para mejoras pequeñas y acotadas; reservar hitos para elegir variantes con contrapartidas. No crear una habilidad nueva en cada nivel. Una variante podría cambiar alcance por daño de Posture o radio por duración, reutilizando las mismas acciones.')
p('La experiencia debería reconocer contribución efectiva del arma que actúa, incluidas defensas útiles, y no simplemente llevarla en la espalda. Falta decidir atribución de efectos persistentes, enemigos demasiado débiles, experiencia defensiva, máximo de nivel, curva, rarezas y materiales. El nivel global del personaje no debe ocultar la identidad de una nueva arma ni hacerla imposible de probar.')
h('Orden recomendado de trabajo')
table(['Prioridad','Entrega y criterio para avanzar'],[['1 Combatir y ajustar','Repetir el Elite con espada, arco y alternancia. Comprobar que se busca parry perfecto, espalda y ruptura; que el arco necesita preparar y no gana por spam o kiteo sin riesgo.'],['2 Playtest actualizado','Compilar menú y región con el combate actual. Probar inicio, audio, controles, muerte y victoria. Recoger arma utilizada, dificultad, claridad y problemas; no distribuir el ZIP antiguo como versión nueva.'],['3 Progresión mínima','Decidir dominio y mejora del objeto, diseñar un recorrido corto y agregar guardado. Poder cambiar de arma, conservar progreso y recuperar la partida sin duplicar recompensas.'],['4 Otra identidad de arma','Probar un martillo acotado como candidato: preparación lenta y castigo de Posture Break. Confirmar su necesidad antes de ampliar el catálogo.'],['5 Profundizar la región','Mejorar telegraphs, recompensas y secreto según playtests; después evaluar nuevas zonas, criaturas y sistemas de largo plazo.']],[.95,5.7])
h('Validación y procedencia')
p('El último ajuste de combate cuenta con 49 comprobaciones automatizadas aprobadas. Existen validaciones previas de armas, presentación, menú y región. Esas pruebas detectan regresiones; no certifican diversión, balance final o rendimiento en equipos ajenos.')
p('Fuentes: GDD original, GDD v0.2, GDD v0.3 consolidado, Combat Design Addendum v0.2, decisiones del autor y documentación de implementación revisada. La v0.4 actualiza esos antecedentes al estado del 8 de septiembre de 2026 y conserva explícitos los pendientes.')
D.core_properties.title='Mismo Game Design Document versión 0.4'; D.core_properties.subject='Diseño consolidado y próximos pasos'; D.core_properties.author=''; D.core_properties.keywords='Mismo, GDD, combate, prototipo'
out=Path('C:/Users/elian/Mismo/Docs/Mismo_GDD_v0.4_consolidado.docx'); D.save(out); print(out)
