import fs from 'node:fs/promises';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
import {resolvePresentationFont,finalizePresentation} from 'file:///C:/Users/elian/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.61513/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root='C:/Users/elian/Mismo', tmp=root+'/.pitch-build';
const skill='C:/Users/elian/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.61513/skills/presentations';
const font=resolvePresentationFont();
const p=Presentation.create({slideSize:{width:1280,height:720}});
const c={bg:'#101A1B',text:'#F1F0E7',sub:'#B7C5C1',accent:'#E6BF75'};
const source='Fuente: Mismo_GDD_v0.7.docx, 13/09/2026. Las ampliaciones de arena, armas únicas y consumibles provienen de la propuesta del autor del 15/09/2026. El estado funcional se basa en el GDD y las capturas del proyecto, no en una nueva prueba de juego.';
function txt(s,t,x,y,w,h,size=28,color=c.text,bold=false){let o=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});o.text=t;o.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none'};return o;}
function slide(title,note=''){let s=p.slides.add();s.background.fill=c.bg;txt(s,title,64,48,1152,112,46,c.text,true);s.speakerNotes.textFrame.setText(source+'\n\n'+note);return s;}
function para(s,head,body,x,y,w=530){txt(s,head,x,y,w,50,30,c.accent,true);txt(s,body,x,y+57,w,133,27,c.text);}
async function img(s,path,x,y,w,h){s.images.add({blob:new Uint8Array(await fs.readFile(root+'/'+path)),contentType:'image/png',alt:'Captura del prototipo Mismo: '+path,fit:'contain',position:{left:x,top:y,width:w,height:h}});}
let s=slide('','Apertura sugerida: Estoy desarrollando Mismo en Unity. Quiero que lo probemos y construyamos juntos una demo que haga visible su potencial.');
txt(s,'MISMO',64,64,620,115,100,c.text,true);txt(s,'Un personaje. Tu estilo nace de las armas.',70,188,1140,65,39,c.accent);await img(s,'.pitch-build/images/2.png',64,290,1152,360);txt(s,'Propuesta para formar equipo',72,666,1100,35,24,c.sub);
s=slide('La experiencia que queremos construir','La fantasía central está en la sección 1 del GDD. La conexión con arena corresponde a la nueva visión. Presentar como una experiencia deseada, no como funciones online terminadas.');
txt(s,'Encontrás un arma que cambia\ncómo te gusta pelear.',64,180,1135,120,48,c.accent,true);
para(s,'En el mundo','Explorás, enfrentás peligros y descubrís equipo. Cada salida puede abrir una forma de jugar.',64,365);
para(s,'Con tus compañeros','La visión 3 vs. 3 lleva esas armas a un equipo, donde importan la práctica y la coordinación.',680,365);
s=slide('El viaje empieza y vuelve al pueblo','Loop actual: pueblo, explorar, recolectar y combatir, administrar mochila, volver para guardar, fabricar o mejorar. La captura es una vista del prototipo de UI y no una promesa de arte final.');
para(s,'La salida','Elegís equipo y explorás. Enemigos, recursos y secretos dan motivos para desviarte.',64,180,460);
para(s,'El regreso','Administrás la mochila, guardás lo valioso y preparás la siguiente expedición.',64,410,460);
await img(s,'.pitch-build/images/4.png',570,190,650,400);txt(s,'El pueblo en el prototipo actual',580,606,640,40,23,c.sub);
s=slide('Las armas definen las habilidades','GDD secciones 2 y 4. Cuatro familias: espada sola, arco, dos espadas, espada y escudo. Dos conjuntos alternables. Cada familia tiene seis opciones y se seleccionan tres. El objeto de habilidad extra sigue abierto en su forma definitiva.');
para(s,'Dos conjuntos alternables','Cada conjunto define el ataque básico y tres habilidades elegidas de su repertorio.',64,180,530);
para(s,'Cuatro familias actuales','Espada, arco, dos espadas y espada con escudo cambian alcance, ritmo y decisiones.',680,180,530);
para(s,'Un objeto adicional','Aporta una habilidad extra independiente del arma. El dash es el punto de partida.',64,435,530);
para(s,'Un mismo personaje','La combinación de equipo permite explorar estilos sin empezar otro personaje.',680,435,530);
s=slide('Un combate que premia aprender','GDD sección 3: lectura, defensas perfectas, Posture y Focus. Explicar sin fórmulas de balance. Captura histórica de prueba de lluvia de flechas, con blanco de test.');
para(s,'Leer al enemigo','Reconocer la preparación del ataque y elegir cuándo esquivar, defender o acercarse.',64,180,570);
para(s,'Crear una oportunidad','Una buena defensa o posición abre espacio para un ataque más comprometido.',64,400,570);
await img(s,'.pitch-build/images/5.png',685,160,540,245);await img(s,'.pitch-build/images/6.png',685,417,540,245);
s=slide('La exploración también crea vínculos','GDD: criaturas, reconocimiento y primera montura de jabalí. Capturas 10 y 11 aportadas por el autor muestran reconocimiento y montura. La ampliación de especies y vínculos queda por diseñar.');
txt(s,'Un encuentro puede terminar con un nuevo compañero de viaje.',64,162,1150,80,34,c.accent);
await img(s,'.pitch-build/images/10.png',64,265,555,270);await img(s,'.pitch-build/images/11.png',665,265,555,270);
txt(s,'Reconocimiento de la criatura',64,560,550,45,27,c.text,true);txt(s,'Primera montura: el jabalí',665,560,550,45,27,c.text,true);
txt(s,'Sistema presente en el prototipo, con movimiento y navegación por pulir.',64,636,1150,48,25,c.sub);
s=slide('Un arma rara puede cambiar la próxima salida','Expansión propuesta por el autor. Ejemplo de experiencia deseada, no contenido implementado. Única significa repertorio especial en esta presentación, no una sola copia existente en todo el mundo. La rareza, probabilidad de obtención y transferencia están por definir.');
txt(s,'Visión en exploración',64,157,1130,42,25,c.accent);
para(s,'Encontrarla','Buscar armas mientras explorás y combatís. Algunas podrían tener movimientos propios.',64,245,530);
para(s,'Aprender a usarla','Descubrir su alcance, sus aperturas y con qué otro equipo combina mejor.',680,245,530);
txt(s,'Llevarla a la arena sería posible solo si la tenés en tu inventario.',64,498,1150,100,36,c.accent,true);
txt(s,'Rareza y condiciones de obtención todavía por definir.',64,633,1150,40,24,c.sub);
s=slide('La expansión: arena 3 vs. 3','Propuesta nueva. No hay evidencia de networking ni PvP implementados. Los equipos pueden coordinar control, presión y distancia sin clases rígidas. El GDD prioriza single-player y luego cooperativo antes de PvP. No prometer fecha.');
txt(s,'3 vs. 3',64,195,550,130,102,c.accent,true);
txt(s,'Tu equipo del mundo\nentra en juego con otros.',64,350,535,120,36,c.text);
para(s,'Antes de la partida','Elegís armas, el objeto de habilidad extra y consumibles iniciales limitados.',690,180,520);
para(s,'Durante la partida','Combinás tu repertorio con el de tus compañeros y decidís cuándo gastar recursos.',690,408,520);
txt(s,'Expansión futura. Requiere multijugador y pruebas propias.',64,641,1140,40,24,c.sub);
s=slide('La decisión clave del PvP: acceso y equilibrio','Estas son propuestas para conversar, no decisiones del autor. Mantener el requisito de poseer el arma. Normalizar estadísticas podría conservar movimientos únicos sin trasladar todas las diferencias de poder. Se deben definir reglas para consumibles, integridad del inventario y autoridad del servidor.');
para(s,'Lo que queremos conservar','La satisfacción de encontrar un arma y llevar una combinación propia al online.',64,180,540);
para(s,'Lo que debemos resolver','Cuánto influye el tiempo de farmeo frente a la habilidad del jugador y del equipo.',680,180,530);
txt(s,'Propuesta para probar',64,425,1150,50,30,c.accent,true);
txt(s,'Conservar movimientos únicos, ensayar estadísticas normalizadas y fijar un cupo de consumibles por partida.',64,486,1140,105,34,c.text);
s=slide('Ya existe una base en Unity','Estado según GDD 0.7 y capturas. No afirmar que las pruebas aisladas certifican estabilidad o calidad. Captura de armas: Artifacts/UI/quiet-armas.png, UI de prototipo. Falta build actual, revisión de animaciones, balance, navegación y rendimiento.');
txt(s,'El prototipo ya reúne',64,173,535,50,31,c.accent,true);
txt(s,'Movimiento y cámara\nCombate y repertorios de armas\nExploración por sectores\nInventario y guardado\nRecolección y crafting básico',64,241,550,270,29,c.text);
txt(s,'Falta pulir la experiencia y unificar el arte.',64,550,530,95,30,c.accent,true);
await img(s,'Artifacts/UI/quiet-armas.png',650,185,570,395);txt(s,'Interfaz de armas del prototipo',660,604,555,40,23,c.sub);
s=slide('El próximo hito: una demo que invite a repetir','Propuesta de alcance para acordar con el equipo. No es calendario ni presupuesto. Una región pequeña, dos estilos contrastantes y una recompensa que cambie una decisión. Registrar si los jugadores entienden el combate, cambian equipo y desean repetir. Online requiere además una prueba técnica temprana separada, sin comprometerlo en esta demo.');
para(s,'Alcance propuesto','Una zona cuidada, dos estilos bien pulidos y un encuentro memorable con recompensa.',64,180,535);
para(s,'Qué queremos comprobar','¿Se entiende el combate? ¿Cambiar de arma resulta interesante? ¿Dan ganas de volver?',680,180,530);
para(s,'Trabajo inmediato','Actualizar la build, mejorar animaciones y feedback, elegir assets coherentes y probar con compañeros.',64,420,535);
para(s,'Camino al online','Evaluar aparte la sincronización de movimiento, impactos e inventario antes de ampliar a seis jugadores.',680,420,530);
s=slide('Dónde puede aportar cada compañero','Áreas sugeridas, no vacantes formales ni compromisos de contratación. Invitar a una contribución concreta y acotada. Antes de asumir responsabilidades, acordar disponibilidad, propiedad y forma de colaborar. No presentar esos acuerdos como ya resueltos.');
para(s,'Arte y animación','Dar identidad al personaje, las armas y el entorno. Mejorar cómo se leen los ataques.',64,180,535);
para(s,'Diseño y pruebas','Ajustar encuentros y repertorios. Observar dónde el juego confunde o deja de divertir.',680,180,530);
para(s,'Desarrollo','Pulir sistemas actuales y estudiar qué exige el futuro multijugador.',64,423,535);
para(s,'Primer compromiso','Elegir una mejora concreta, acordar disponibilidad y probar el resultado juntos.',680,423,530);
s=slide('La invitación','Cierre sugerido: Quiero que prueben lo que ya está, me digan qué les entusiasma y elijamos una parte pequeña para mejorar juntos. Si la demo genera ganas de volver, tendremos una base más convincente para buscar comunidad y financiación.');
txt(s,'Construyamos una demo\nque queramos seguir jugando.',64,191,1130,165,58,c.accent,true);
txt(s,'Ya hay una base. La próxima decisión es qué parte\nqueremos llevar juntos a una experiencia convincente.',64,432,1130,115,34,c.text);
txt(s,'Probar el juego y elegir la primera mejora compartida.',64,612,1150,45,27,c.sub);
s=slide('Anexo: antecedentes de crowdfunding','Fuentes consultadas el 15/09/2026. https://www.kickstarter.com/projects/projectgorgon/project-gorgon-pc-mmo : USD 74.781, meta USD 20.000, 1.318 aportantes, campaña 2015. https://www.kickstarter.com/projects/1661802484/hyper-light-drifter : USD 645.158, meta USD 27.000, 24.150 aportantes, campaña 2013. Afinidad interpretativa: fantasía/exploración y aventura/exploración. No son equivalentes al concepto completo de Mismo. Recaudación bruta de campaña, no beneficio ni presupuesto total.');
para(s,'Project: Gorgon','Fantasía y descubrimiento.\nCampaña de 2015 en Kickstarter.\nMeta: USD 20.000.',64,177,540);
txt(s,'USD 74.781',64,387,540,74,48,c.accent,true);
para(s,'Hyper Light Drifter','Aventura y exploración.\nCampaña de 2013 en Kickstarter.\nMeta: USD 27.000.',680,177,540);
txt(s,'USD 645.158',680,387,540,74,48,c.accent,true);
txt(s,'Son antecedentes parciales, no una estimación de lo que recaudaría Mismo.',64,517,1150,95,31,c.text);
txt(s,'Importes brutos de campaña. Fuentes y enlaces en las notas.',64,640,1150,40,23,c.sub);
await fs.writeFile(tmp+'/presentation.json',JSON.stringify(p.toProto()));
await (await PresentationFile.exportPptx(p)).save(tmp+'/candidate.pptx');
const result=await finalizePresentation({workspaceDir:root,candidatePath:tmp+'/candidate.pptx',finalPath:root+'/output/Mismo-Pitch/Mismo_Presentacion_Equipo.pptx',pythonExecutable:'C:/Users/elian/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-bullet-geometry','--validate-heading-fit'],fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:tmp+'/validation.json'});
console.log(JSON.stringify(result));
for(let i=0;i<p.slides.items.length;i++){const b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(tmp+`/slide-${i+1}.png`,new Uint8Array(await b.arrayBuffer()));}
console.log('DONE '+font);

